apiVersion: v1
kind: Service
metadata:
  name: nodeapp-srv
  namespace: aathishtest1
spec:
  selector:
    app: node-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
  type: LoadBalancer
